# Generated by Django 3.2.3 on 2021-05-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodGroup',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
