# Generated by Django 3.2.3 on 2021-05-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_patient_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointDate',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
