# Generated by Django 3.2.3 on 2021-05-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
