# Generated by Django 3.2.3 on 2021-05-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
