# Generated by Django 3.2.3 on 2021-05-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_patient_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
    ]
