# Generated by Django 3.2.3 on 2021-05-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210527_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='original.jpg', null=True, upload_to=''),
        ),
    ]
