# Generated by Django 3.2.3 on 2021-05-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_doctor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointDate',
            field=models.DateTimeField(null=True),
        ),
    ]
